In [ ]:
# Lab 1-1

def fibonacciRecur(x):
  if (x<=0) :
    return 0 
  if x==1:
    return 1
  else :
    return fibonacciRecur(x-1)+fibonacciRecur(x-2)


def fibonacciIter(x):
  f1=0
  f2=1
  t=f1+f2
  if x == 0:
    print(0)
  if x==1:
    print(1)
  if x==2:
    print(2)
  
  for i in range(3,x+1):
    f1=f2
    f2=t
    t=f1+f2
  print("Iterative = ",t)

print("Please Input Your Number (Positive Number)");
x = int(input())
fibonacciIter(x)

print("Recursive = " , fibonacciRecur(x))

Please Input Your Number (Positive Number)
7
Iterative =  13
Recursive =  13


In [2]:
# Lab 1-2

import numpy as np
def LCS(x,y):
  n1 = len(x)
  n2 = len(y)
  c = np.zeros((n1+1,n2+1))

  # print(c)
  for i in range(0,n1):
    for j in range(0,n2):

      if x[i] == y[j]:
        c[i+1,j+1] = c[i,j]+1
      else:
        c[i+1,j+1] = max(c[i,j+1],c[i+1,j])
  return c

# Done
def backtrack(c, x, y, i, j):
  # print("Current at",i," ",j)
  if i==0 or j==0:
    return ""
  if x[i-1] == y[j-1]:
    return backtrack(c,x,y,i,j-1)+x[i-1]
  if c[i,j-1] > c[i-1,j]:
    return backtrack(c,x,y,i,j-1)

  return backtrack(c,x,y,i-1,j)

seq1 = 'XMJYAUZ'
seq2 = 'MZJAWXU'
# seq1 = 'abcab'
# seq2 = 'aabaca'
len1 = len(seq1)
len2 = len(seq2)

c = LCS(seq1,seq2)
# print(c)
print(backtrack(c,seq1,seq2,len1,len2))
print(c)


MJAU
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 2. 2. 2. 2. 2.]
 [0. 1. 1. 2. 2. 2. 2. 2.]
 [0. 1. 1. 2. 3. 3. 3. 3.]
 [0. 1. 1. 2. 3. 3. 3. 4.]
 [0. 1. 2. 2. 3. 3. 3. 4.]]


In [1]:
#Lab 1-3 Coin Exchange

import numpy as np

coin = [1,2,5,10]
def returnCoin(changes):
  matrix = np.zeros((4,changes+1))
  for i in range(4):
    for j in range(1,changes+1):
      if i==0:
        matrix[i,j] = j
      else:
        matrix[i,j] = matrix[i-1,j]
        if j>=coin[i]:
          matrix[i,j] = matrix[i,j-coin[i]]+1
  return matrix

def backwardCoin(matrix,i,j):
  # print("Current At ",i," " ,j)
  if j<=0 or i<=0:
    if(i<=0):
      return str(coin[0])+" "
    return ""
  if matrix[i-1,j] == matrix[i,j]:
    return backwardCoin(matrix,i-1,j)
  return backwardCoin(matrix,i,j-coin[i])+str(coin[i])+" "

print("Return Changes:",end="")
changes = int(input())
matrix = returnCoin(changes)
print(matrix)
print("\nCoin Changes is "+backwardCoin(matrix,4-1,changes))

Return Changes:14
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
 [ 0.  1.  1.  2.  2.  3.  3.  4.  4.  5.  5.  6.  6.  7.  7.]
 [ 0.  1.  1.  2.  2.  1.  2.  2.  3.  3.  2.  3.  3.  4.  4.]
 [ 0.  1.  1.  2.  2.  1.  2.  2.  3.  3.  1.  2.  2.  3.  3.]]

Coin Changes is 2 2 10 


In [ ]:
from google.colab import drive
drive.mount('/content/drive')