In [233]:
import numpy as np
import math

def dist(a,b):
  return ( (a[0]-b[0])**2 + (a[1]-b[1])**2 )**(1/2)

def roundList(elist):
  for i in range(len(elist)):
    for j in range(len(elist[0])):
      elist[i,j] = round(elist[i,j],5)
  return elist

# DONE
def fuzzyCMeans(data):
  k1 = (6,7)
  k2 = (1,10)
  k3 = (7,5)
  k=3
  n = len(data)
  partition = np.random.rand(n,k)
  part_sum_row = partition.sum(axis=1)

  norm_part = partition/part_sum_row[:,np.newaxis]
  print(part_sum_row)
  
  norm_part_temp=[]

  iter = 150
  print("Start>>>")
  for cycle in range(iter):
    norm_part_temp = norm_part.copy()
    print("\n>>> Current Loop ",cycle,".")
    print("Patrition Matrix [ Before Update ]")
    print(norm_part)
    # calculate new k-means
    new_k=[]
    for j in range(k):
      ki1=0
      ki2=0
      sum_p=0
      for i in range(n):
        ki1 = ki1 + data[i][0] * (norm_part[i,j])**2
        ki2 = ki2 + data[i][1] * (norm_part[i,j])**2
        sum_p = sum_p+((norm_part[i,j])**2)
      ki1_new = ki1/sum_p
      ki2_new = ki2/sum_p
      new_k.append((ki1_new,ki2_new))

    print(".")
    print("New K-Means >>> ",new_k)

    # update partition
    for i in range(n):
      for j in range(k):
        x=dist(data[i],new_k[j])
        ki0=dist(data[i],new_k[0])
        ki1=dist(data[i],new_k[1])
        ki2=dist(data[i],new_k[2])
        norm_part[i,j] = 1/( (x/(ki0+ki1+ki2))**2 )

    # print("\SS>>>\n",norm_part)
    # print("\nTemp>>>\n",norm_part_temp)
    print("Patrition Matrix [ After Update ]")
    part_sum_row = norm_part.sum(axis=1)
    norm_part_new = norm_part/part_sum_row[:,np.newaxis]

    norm_part_temp = roundList(norm_part_temp)
    norm_part_new = roundList(norm_part_new)

    # print("temp = \n",norm_part_temp)
    # print(norm_part_new)

    isTrue = norm_part_new == norm_part_temp
    # print(isTrue)
    # print(isTrue.all())

    if isTrue.all():
      print(cycle,"________END of Cycle________")
      break
    else:
      # print("isTrue = ",isTrue)
      norm_part = norm_part_new
      print(norm_part)
      print("Continue>>")

  print("\nOutput:\nK-Means >> ",new_k)    
  print("Partition Matrix")
  print(norm_part_new)

data = [(7,8),(25,16),(13,2),(9,17),(1,1),(15,7),(8,1),(9,2),(11,7),(1,7)]

fuzzyCMeans(data)




[1.32539055 1.08857041 1.44470204 1.27911697 0.96604304 1.17452573
 1.50238282 1.16466523 1.50509832 1.16709701]
Start>>>

>>> Current Loop  0 .
Patrition Matrix [ Before Update ]
[[0.44467487 0.19753289 0.35779224]
 [0.15438886 0.43898811 0.40662303]
 [0.09342469 0.23874358 0.66783172]
 [0.51594003 0.12673856 0.3573214 ]
 [0.48853993 0.1627505  0.34870958]
 [0.30330414 0.54829902 0.14839684]
 [0.55639538 0.41205417 0.03155045]
 [0.18028017 0.11430993 0.70540991]
 [0.22906565 0.37602407 0.39491028]
 [0.53883909 0.00077624 0.46038467]]
.
New K-Means >>>  [(6.444530442975473, 6.7212878264407365), (14.164622199081187, 7.424673873075063), (10.037771972347382, 5.6358702076982805)]
Patrition Matrix [ After Update ]
[[0.85558 0.03219 0.11223]
 [0.21962 0.49505 0.28533]
 [0.16427 0.34828 0.48745]
 [0.35596 0.33738 0.30665]
 [0.52763 0.15337 0.31899]
 [0.01147 0.95681 0.03173]
 [0.35534 0.15756 0.4871 ]
 [0.28331 0.14555 0.57114]
 [0.09508 0.19425 0.71067]
 [0.65485 0.11218 0.23297]]
Continue>>